server:
  port: 9090
  servlet:
    contextPath: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RUNHI_DB_URL}
    username: ${RUNHI_DB_USER}
    password: ${RUNHI_DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

decorator:
  datasource:
    p6spy:
      enable-logging: true

#JWT
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration-time: ${ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token-expiration-time: ${REFRESH_TOKEN_EXPIRATION_TIME}
